name: 'Terraform Destroy'

on:
  workflow_dispatch:
env:
    ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    TF_LOG: INFO
    TF_INPUT: false
    # TF_IN_AUTOMATION: true
permissions:
    contents: read
    id-token: write
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    #use bash shell regardless of github actions runner 
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
# Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
# Destroys the file in Azure Blob Storage
    - name: Delete file from Azure Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --name terraform_vars.txt --container-name ${{ secrets.CONTAINER_NAME }}