name: 'Terraform Apply'
# used GH copilot chat to create this template for me
# action that provisions infrastructure to Azure
on:
    push:
        branches:
            - main
        paths:
            - '**.tf'
    workflow_dispatch:

env:
    ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    TF_LOG: INFO
    TF_INPUT: false
    TF_IN_AUTOMATION: true

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
    
    - name: Export Terraform Outputs
      id: tf
      run: |
          echo "API_KEY=$(terraform output api_key)"
          echo "WEBAPP_NAME=$(terraform output webapp_name)"
          echo "OUTPUT_ID=$(terraform output id)"
          echo "RESOURCE_GROUP=$(terraform output resource_group_name)"
    outputs:
        API_KEY: ${{ steps.tf.outputs.API_KEY }}
        WEBAPP_NAME: ${{ steps.tf.outputs.WEBAPP_NAME }}
        OUTPUT_ID: ${{ steps.tf.outputs.OUTPUT_ID }}
        RESOURCE_GROUP: ${{ steps.tf.outputs.RESOURCE_GROUP }}