name: 'Terraform Plan'

on:
    push:
        branches:
            - dev
        paths:
            - '**.tf'
    workflow_dispatch:

env:
    ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
    ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
    ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    TF_LOG: INFO
    TF_INPUT: false
    TF_IN_AUTOMATION: true

permissions:
  contents: read
  id-token: write
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    #use bash shell regardless of github actions runner 
    defaults:
      run:
        shell: bash
# clone repo to runner machine 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
# setup terraform on runner machine
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0
#initialize terraform
    - name: Terraform Init
      run: terraform init
# Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
# run terraform validate even if fmt is bad 
    - name: Terraform Validate
      id: validate
      if: (success()||failure())
      run: terraform validate
# run terraform plan if validate is successful
    - name: Terraform Plan
      run: terraform plan